### ISSUE TITLE
Add cohosts to hacky hour zoom

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#24]
@kerry-tarrant: I noticed your entry in the text file in #23 does not have an associated email, I'm curious if that's related to why you cannot see the hacky hour meetings in your zoom profile. (even though I have your email listed).

When I added marco, I had to add `mpipoly@uiowa.edu` and not his real email, but when I tried to add `kdtarrant@uiowa.edu` it says that "email" is not associated with a zoom account. Don't know if that's helpful or not. **EDIT**: had to add everyone else with their real email, marco's email was the odd one out.

I'll add the rest of the brainhack committee as alternative hosts to the zoom sessions as well.

**Comment by kerry-tarrant** [comment]
@jdkent I see what you're talking about. I believe I signed up with my kerry-tarrant [at] uiowa.edu email. Also, it might be the case that I wasn't signed in during that session and that's why my email didn't show up in the report. I thought I was, but I can't recall though. 

When I'm signed in through the browser to access meeting information from Zoom's website, I didn't notice any meetings shared to me. This might because you used kdtarrant instead of kerry-tarrant.

I hope this helps.

**Comment by jdkent** [comment]
I think this task is as completed as it can be...
